services:
  youtubematic:
    build: .
    user: "${UID:-501}:${GID:-20}"
    volumes:
      - ./downloads:/mnt/downloads
    environment:
      - DOWNLOAD_PATH=/mnt/downloads
      - CHANNELS=https://www.youtube.com/@LowkoTV
      - MAX_EPISODES=2
      - MAX_AGE_DAYS=${MAX_AGE_DAYS:-}
      - YT_DLP_PATH=${YT_DLP_PATH:-yt-dlp}
    restart: no
